//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhixerShipments.Facade.ServiceWantToTake {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWantToTake.IServiceWantToTake")]
    public interface IServiceWantToTake {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWantToTake/Ping", ReplyAction="http://tempuri.org/IServiceWantToTake/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWantToTake/Ping", ReplyAction="http://tempuri.org/IServiceWantToTake/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWantToTakeChannel : WhixerShipments.Facade.ServiceWantToTake.IServiceWantToTake, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWantToTakeClient : System.ServiceModel.ClientBase<WhixerShipments.Facade.ServiceWantToTake.IServiceWantToTake>, WhixerShipments.Facade.ServiceWantToTake.IServiceWantToTake {
        
        public ServiceWantToTakeClient() {
        }
        
        public ServiceWantToTakeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWantToTakeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWantToTakeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWantToTakeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
